# Generated by Django 4.1.3 on 2023-01-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about_me',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='Hello world!', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+996 900 000 000', max_length=20, null=True),
        ),
    ]
