# Generated by Django 4.1.3 on 2023-01-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='last_message',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='message',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
